### ISSUE TITLE
Using FudgeNet for a game causes the editor to fail to open

### ISSUE THREAD

**Issue by Plagiatus** [hs-furtwangen/FUDGE#17]
When using FudgeNet [like in this file / project](https://github.com/Motivationline/BrawlLike/blob/main/Script/Source/Managers/MultiplayerManager.ts), I'm unable to start the FUDG Editor due to this ReferenceError:

![grafik](https://github.com/user-attachments/assets/1d28a70d-a0bc-4cac-b2a3-6486a1b5aa36)

This obviously hinders the development of multiplayer games dramatically.

**Comment by JirkaDellOro** [comment]
The editor doesn't now FudgeNet yet. Add the following line to the Fudge.html in Editor/Html

`  <script type="text/javascript" src="../../Distribution/FudgeClient.js"></script>`

**Comment by Plagiatus** [comment]
should I add this or wait for your dev branch to get merged? since you've assigned me I assume I should just quickly fix it myself?

**Comment by JirkaDellOro** [comment]
That was just to remind you to close the issue, when it's done. I did the fix to my devJirka branch, so we either wait for this to be merged or you might do a fix on main.
