### ISSUE TITLE
CustomTree vs. Tree

### ISSUE THREAD

**Issue by JirkaDellOro** [hs-furtwangen/FUDGE#18]
Discussion
- when should one use Tree over CustomTree?
- if both remain, shouldn't one extend the other to share code?
- CustomTree sound unspecific, how about TreeSortable or similar?

**Comment by plojo** [comment]
My plan is to completly replace Tree with CustomTree. I have already replaced all occurences of the old Tree with CustomTree (ViewExternal, ViewInternal, ViewHierarchy, ViewParticleSystem). However there are some thing left to do:

- [ ] Verify keyboard controls for the new CustomTree
- [ ] Add a sortable flag to the CustomTreeController to allow opt-out of sortable (ViewExternal doesn't allow sorting).
- [ ] Rename remove the old Tree. Rename CustomTree to Tree

**Comment by JirkaDellOro** [comment]
A checkmark means it has been done or it will be done? 
I'm refactoring drag&drop and copy&paste and would continue once the tree is ready for it

**Comment by plojo** [comment]
CHeckmark means it is done. I just pushed the last changes. Will close the issue.
