### ISSUE TITLE
node.replaceChild doesn't properly remove child & its components

### ISSUE THREAD

**Issue by Plagiatus** [hs-furtwangen/FUDGE#19]
I've used `node.replaceChild` in the linked project, in this specific line and commit: https://github.com/Motivationline/BrawlLike/blob/ea3969076feff1eeec3eb792ec08c07d17056397/Script/Source/Destructible.ts#L23

I've since replaced it with a `node.removeChild` + `node.addChild` as `node.replaceChild` left behind the hitboxes from the previous child.

To explain what's in the images:   
I have a box with the linked `Destructible` component that places a different graph in its position when the `destroy` function is called. In the first image you can see this working using the removeChild + addChild method, where only the undestroyed box has the hitbox around it. In the second picture, the one taken from the commit linked above, the hitbox is still present even on the destroyed objects.

_Don't mind the fact that they are seemingly different models, that's all the same double-plank model loaded through the same graph, which just doesn't load right. But that's a different issue._

![grafik](https://github.com/user-attachments/assets/1aff1b24-53d9-4856-9e7e-be13f512c41d)

![grafik](https://github.com/user-attachments/assets/a13e3b1f-9db1-45d7-af35-2dc44093878f)

**Comment by JirkaDellOro** [comment]
Please test, main branch

**Comment by Plagiatus** [comment]
seems to work as intended now.
