### ISSUE TITLE
Enhancement: "getScaled()" in addition to "scale()" for Vectors, which returns a cloned instance of the scaled Vector instead of changing it

### ISSUE THREAD

**Issue by CalvinDO** [hs-furtwangen/FUDGE#47]

**Comment by Plagiatus** [comment]
you can use the static `Vector.SCALE()` function for that purpose.

**Comment by CalvinDO** [comment]
Thanks, should i close the issue? 
Am 23-Dec-2024 20:33:32 +0100 schrieb ***@***.***: 

  you can use the static `Vector.SCALE()` function for that purpose. 

--
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID:   

-------------------------------------------------------------------------------------------------
FreeMail powered by mail.de - MEHR SICHERHEIT, SERIOSITÄT UND KOMFORT
