### ISSUE TITLE
Adding/Deleting nodes doesn't show in render view

### ISSUE THREAD

**Issue by JirkaDellOro** [hs-furtwangen/FUDGE#6]
Interaction with the renderview needed to see the effect.

appearently introduced with commit
Date:   Fri Mar 22 15:51:04 2024 +0100
cleanup unused listerner and handler

**Comment by plojo** [comment]
Seems like these listeners weren't so unused after all...

**Comment by JirkaDellOro** [comment]
Yes. How did you test to determine that they are unused?

**Comment by plojo** [comment]
I tested various user interactions but i must've had the "Render Contiously" flag set, so didn't notice the missing scene draws.

**Comment by JirkaDellOro** [comment]
Better to set conditional breakpoints or outputs that react to spefic events
